#!/bin/sh
 
ssh hector@ubuntu <<EOF
  cd ~/jenkins/hello-jenkins
#  git pull
#  npm install --production
  pid=`ps aux | grep 'nodejs app.js' | head -1 |  awk '{print $2}'`
  kill -9 $pid
  node app.js
  exit
EOF
